[package]
name = "server"
version = "0.1.0"
authors = ["Gabington Crusoe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wait-timeout = "0.1.5"
actix-web = "3"
log = "0.4"
pretty_env_logger = "0.4"
